### ISSUE TITLE
gyroscope not working on safari

### ISSUE THREAD

**Issue by lavish0000** [mkosir/react-parallax-tilt#10]
Gyroscope is not working in safari , version 13.
I even opened this demo in safari mobile.
"https://mkosir.github.io/react-parallax-tilt/?path=/story/react-parallax-tilt--gyroscope-tilt",
even this is not working either.
can you please help me to fix this issue.
I am using iphone X for this.

**Comment by mkosir** [comment]
Hi @lavish0000, you can try and update library newest version `1.4.54`.
With iOS 13+ devices permission API can be used to gain access to device orientation event. Apple decided turning device motion and orientation off by default since iOS 12.2.
[Updated docs.](https://github.com/mkosir/react-parallax-tilt#gyroscope---device-orientation)

**Comment by mkosir** [comment]
Closing this issue since inactivity, feel free to reopen it!

**Comment by gavan1** [comment]
adding the gyroscope flag and serving over https does not display the prompt.

This [link](https://kongmunist.medium.com/accessing-the-iphone-accelerometer-with-javascript-in-ios-14-and-13-e146d18bb175) might help you fix the feature.
